"""UI copy. Romanian is the product language (decision 2026-09-17); English is a
toggle. Every key exists in both tables — the test suite renders both."""

STRINGS = {
    "ro": {
        "app": "e-Factura Sync",
        "nav_home": "Acasă",
        "nav_invoices": "Facturi",
        "nav_settings": "Setări",
        "sync": "Sincronizează",
        "sync_running": "Sincronizare în curs…",
        "sync_busy": "O sincronizare este deja în curs.",
        "last_sync": "Ultima sincronizare",
        "never": "niciodată",
        "total": "Facturi descărcate",
        "this_month": "Luna aceasta",
        "pdf_failed": "PDF nereușite",
        "environment": "Mediu",
        "recent": "Cele mai recente",
        "log": "Jurnal",
        "open_pdf": "Deschide PDF",
        "xml_only": "doar XML",
        "col_date": "Data",
        "col_invoice": "Factura",
        "col_supplier": "Furnizor",
        "col_type": "Tip",
        "credit_note": "notă de credit",
        "invoice": "factură",
        "filter_month": "Luna",
        "filter_supplier": "Furnizor",
        "all": "toate",
        "filter": "Filtrează",
        "open_folder": "Deschide dosarul",
        "no_invoices": "Nicio factură descărcată încă.",
        "csv_note": "Fișierul invoices.csv din dosar conține toate facturile pentru contabilitate.",
        "settings": "Setări",
        "settings_saved": "Setările au fost salvate.",
        "config_needed": "Completează setările pentru a începe.",
        "client_id": "Client ID",
        "client_secret": "Client secret",
        "secret_keep": "lasă gol pentru a păstra valoarea existentă",
        "secret_set": "(setat)",
        "cif": "CIF",
        "cif_hint": "doar cifre, fără RO",
        "environment_prod": "Producție",
        "environment_test": "Test",
        "redirect_uri": "Callback URL",
        "base_dir": "Dosarul pentru facturi",
        "save": "Salvează",
        "auth": "Autentificare ANAF",
        "auth_yes": "Autentificat",
        "auth_no": "Neautentificat",
        "expires": "expiră",
        "auth_begin": "Începe autentificarea",
        "auth_step1": "Deschide adresa de mai jos într-un browser în care este disponibil certificatul digital calificat.",
        "auth_step2": "Autentifică-te cu certificatul și autorizează aplicația.",
        "auth_step3": "Vei fi redirecționat către callback URL (pagina poate să nu se încarce — este normal). Copiază adresa completă din bara de adrese și lipește-o mai jos.",
        "paste": "Lipește adresa de redirecționare",
        "auth_complete": "Finalizează",
        "auth_ok": "Autentificare reușită.",
        "error": "Eroare",
        "language": "Limbă",
        "quit": "Închide aplicația",
        "quit_bye": "Aplicația s-a închis. Poți închide această fereastră.",
        "ev_started": "Se listează facturile primite din ultimele {days} zile ({env}, CIF {cif})…",
        "ev_listed": "{count} mesaj(e) returnate de ANAF.",
        "ev_done": "{invoice} — {supplier} ({date})",
        "ev_dup": "Ignorat (deja descărcat): {id}",
        "ev_pdf_failed": "PDF nereușit pentru {invoice}: {message}",
        "ev_error": "Eroare la {id}: {message}",
        "ev_error_run": "Eroare: {message}",
        "ev_notice": "{message}",
        "ev_finished": "Gata: {new} noi, {dup} duplicate, {pdf} PDF nereușite, {err} erori.",
    },
    "en": {
        "app": "e-Factura Sync",
        "nav_home": "Home",
        "nav_invoices": "Invoices",
        "nav_settings": "Settings",
        "sync": "Synchronize",
        "sync_running": "Sync in progress…",
        "sync_busy": "A sync is already running.",
        "last_sync": "Last sync",
        "never": "never",
        "total": "Invoices downloaded",
        "this_month": "This month",
        "pdf_failed": "PDF failures",
        "environment": "Environment",
        "recent": "Most recent",
        "log": "Log",
        "open_pdf": "Open PDF",
        "xml_only": "XML only",
        "col_date": "Date",
        "col_invoice": "Invoice",
        "col_supplier": "Supplier",
        "col_type": "Type",
        "credit_note": "credit note",
        "invoice": "invoice",
        "filter_month": "Month",
        "filter_supplier": "Supplier",
        "all": "all",
        "filter": "Filter",
        "open_folder": "Open folder",
        "no_invoices": "No invoices downloaded yet.",
        "csv_note": "invoices.csv in the folder lists every invoice for accounting.",
        "settings": "Settings",
        "settings_saved": "Settings saved.",
        "config_needed": "Fill in the settings to get started.",
        "client_id": "Client ID",
        "client_secret": "Client secret",
        "secret_keep": "leave blank to keep the existing value",
        "secret_set": "(set)",
        "cif": "CIF",
        "cif_hint": "digits only, no RO",
        "environment_prod": "Production",
        "environment_test": "Test",
        "redirect_uri": "Callback URL",
        "base_dir": "Invoices folder",
        "save": "Save",
        "auth": "ANAF authentication",
        "auth_yes": "Authenticated",
        "auth_no": "Not authenticated",
        "expires": "expires",
        "auth_begin": "Start authentication",
        "auth_step1": "Open the address below in a browser where your qualified digital certificate is available.",
        "auth_step2": "Authenticate with the certificate and authorize the application.",
        "auth_step3": "You will be redirected to the callback URL (the page may not load — that is normal). Copy the full address from the address bar and paste it below.",
        "paste": "Paste the redirect address",
        "auth_complete": "Complete",
        "auth_ok": "Authentication successful.",
        "error": "Error",
        "language": "Language",
        "quit": "Quit the app",
        "quit_bye": "The app has quit. You can close this window.",
        "ev_started": "Listing received invoices from the last {days} days ({env}, CIF {cif})…",
        "ev_listed": "{count} message(s) returned by ANAF.",
        "ev_done": "{invoice} — {supplier} ({date})",
        "ev_dup": "Skipped (already downloaded): {id}",
        "ev_pdf_failed": "PDF failed for {invoice}: {message}",
        "ev_error": "Error on {id}: {message}",
        "ev_error_run": "Error: {message}",
        "ev_notice": "{message}",
        "ev_finished": "Done: {new} new, {dup} duplicates, {pdf} PDF failures, {err} errors.",
    },
}

LANGUAGES = tuple(STRINGS)


def translator(lang: str):
    table = STRINGS.get(lang) or STRINGS["ro"]

    def t(key: str, **fmt) -> str:
        text = table.get(key) or STRINGS["ro"].get(key, key)
        return text.format(**fmt) if fmt else text

    return t
