"""UI copy. Romanian is the product language (decision 2026-09-17); English is a
toggle. Every key exists in both tables — the test suite renders both."""

STRINGS = {
    "ro": {
        "app": "e-Factura Sync",
        "nav_home": "Acasă",
        "nav_invoices": "Facturi",
        "nav_settings": "Setări",
        "sync": "Sincronizează",
        "sync_running": "Sincronizare în curs…",
        "sync_busy": "O sincronizare este deja în curs.",
        "last_sync": "Ultima sincronizare",
        "never": "Niciodată",
        "total": "Facturi descărcate",
        "this_month": "Luna aceasta",
        "pdf_failed": "Facturi fără PDF",
        "environment": "Mediu",
        "recent": "Ultimele facturi descărcate",
        "log": "Jurnal",
        "open_pdf": "PDF",
        "xml_only": "fără PDF",
        "no_pdf": "fără PDF",
        "no_pdf_why": "ANAF nu a putut genera PDF-ul. Fișierul original al facturii este în dosar și este valabil pentru contabilitate.",
        "col_date": "Data",
        "col_invoice": "Factura",
        "col_supplier": "Furnizor",
        "col_type": "Tip",
        "credit_note": "storno",
        "credit_note_long": "Notă de creditare (factură storno)",
        "invoice": "factură",
        "filter_month": "Luna",
        "filter_supplier": "Furnizor",
        "all": "toate",
        "filter": "Filtrează",
        "open_folder": "Deschide dosarul",
        "no_invoices": "Nicio factură descărcată încă. Mergi la Acasă și apasă Sincronizează.",
        "no_invoices_filtered": "Nicio factură nu corespunde filtrelor.",
        "clear_filters": "Șterge filtrele",
        "months": "ianuarie,februarie,martie,aprilie,mai,iunie,iulie,august,septembrie,octombrie,noiembrie,decembrie",
        "csv_note": "Fișierul invoices.csv din dosar cuprinde toate facturile — îl poți trimite contabilului.",
        "settings": "Setări",
        "settings_saved": "Setările au fost salvate.",
        "config_needed": "Completează setările pentru a începe.",
        "client_id": "Client ID",
        "client_secret": "Client secret",
        "secret_keep": "lasă gol pentru a păstra valoarea existentă",
        "secret_set": "(setat)",
        "cif": "CUI (cod fiscal)",
        "cif_hint": "doar cifre, fără RO",
        "environment_prod": "Producție (facturi reale)",
        "environment_test": "Test",
        "redirect_uri": "Callback URL",
        "base_dir": "Dosarul pentru facturi",
        "save": "Salvează",
        "auth": "Autentificare ANAF",
        "auth_yes": "Autentificat",
        "auth_no": "Neautentificat",
        "expires": "valabilă până la {date} (se reînnoiește automat)",
        "auth_begin": "Începe autentificarea",
        "auth_step1": "Deschide adresa de mai jos într-un browser în care este disponibil certificatul digital calificat.",
        "auth_step2": "Autentifică-te cu certificatul și autorizează aplicația.",
        "auth_step3": "Browserul va încerca să deschidă o adresă care nu se va încărca — este normal. Copiază adresa completă din bara de adrese și lipește-o mai jos.",
        "auth_copy_hint": "Dacă folosești alt browser pentru certificat, copiază adresa și lipește-o acolo.",
        "auth_restart": "Reia autentificarea",
        "auth_not_pending": "Autentificarea nu mai este în curs. Începe-o din nou.",
        "new_tab": "(se deschide într-o filă nouă)",
        "paste": "Lipește adresa de redirecționare",
        "auth_complete": "Finalizează",
        "auth_ok": "Autentificare reușită.",
        "error": "Eroare",
        "tech_details": "Detalii tehnice",
        "language": "Limbă",
        "quit": "Închide aplicația",
        "firm": "Firmă",
        "copy_url": "Copiază adresa",
        "copied": "Copiat.",
        "pdf_retry": "Reîncearcă PDF",
        "pdf_retry_all": "Gata: {done} PDF-uri generate, {failed} încă fără PDF.",
        "pdf_retry_ok": "PDF-ul a fost generat.",
        "pdf_retry_all_btn": "Reîncearcă toate PDF-urile lipsă",
        "filter_missing_pdf": "doar fără PDF",
        "firms": "Firme",
        "firm_name": "Numele firmei",
        "firm_switch": "Schimbă firma",
        "firm_add": "Adaugă firmă",
        "firm_add_hint": "Dosarul facturilor pentru o firmă nouă: Documents/Facturi e-Factura/<numele firmei>. Autentificarea la ANAF este comună: certificatul trebuie să aibă drepturi în SPV pentru fiecare firmă.",
        "firm_select": "Selectează",
        "firm_selected": "selectată",
        "firm_remove": "Șterge",
        "firm_added": "Firma „{name}” a fost adăugată și selectată.",
        "firm_removed": "Firma a fost ștearsă (facturile descărcate rămân în dosar).",
        "firm_last": "Aceasta este ultima firmă; nu poate fi ștearsă.",
        "val_firm_new": "Completează numele firmei și CUI-ul (doar cifre).",
        "diag_title": "Diagnostic",
        "diag_hint": "Dacă ceva nu merge, trimite aceste informații (fără date confidențiale) împreună cu descrierea problemei.",
        "diag_copy": "Copiază informații de diagnostic",
        "diag_copied": "Copiat.",
        "diag_open": "vezi ca text",
        "quit_bye": "Aplicația s-a închis. Poți închide această filă. Pentru a o porni din nou, deschide e-Factura Sync ca de obicei.",
        "switch_lang": "Schimbă limba în engleză",
        "footer_local": "Aplicația rulează pe calculatorul tău, la {url}. Poți închide fila — aplicația rămâne pornită.",
        "open_pdf_for": "PDF pentru factura {invoice} (se deschide într-o filă nouă)",
        "choose_folder": "Alege dosarul pentru facturi",
        "err_page_expired": "Pagina a expirat, probabil pentru că aplicația a fost repornită. Reîncarcă pagina (Cmd+R / F5) și încearcă din nou.",
        "err_pdf_missing": "Fișierul PDF nu mai există în dosar. Deschide dosarul pentru a verifica sau sincronizează din nou.",
        "err_not_found": "Pagina nu există.",
        "err_bad_request": "Cererea nu a putut fi procesată. Reîncarcă pagina și încearcă din nou.",
        "err_server": "A apărut o eroare neașteptată în aplicație. Reîncarcă pagina; dacă persistă, detaliile sunt în ui.log.",
        "secret_retype": "Reintrodu Client secret — din motive de siguranță nu îl păstrăm în formular.",
        # first-run wizard
        "wiz_title": "Configurare inițială",
        "wiz_step": "Pasul {n} din 3",
        "wiz_need_title": "De ce ai nevoie",
        "wiz_need_cert": "Un certificat digital calificat (DigiSign, certSIGN, AlfaTrust…) înregistrat în SPV pentru firma ta, cu e-Factura activată.",
        "wiz_need_app": "O aplicație înregistrată la ANAF (profil OAuth), care îți dă un Client ID și un Client secret:",
        "anaf_api_link": "anaf.ro → Înregistrare API",
        "wiz_back": "← Înapoi",
        "wiz_app_1": "Intră pe anaf.ro → Servicii online → Înregistrare aplicații developeri → Înregistrare în vederea accesării serviciilor web.",
        "wiz_app_2": "Autentifică-te în SPV (certificat sau utilizator/parolă).",
        "wiz_app_3": "Creează un profil OAuth: nume aplicație, Callback URL (folosește https://localhost/callback) și bifează serviciul EFACTURA.",
        "wiz_app_4": "Generează și copiază Client ID și Client secret — le introduci la pasul următor.",
        "wiz_next": "Continuă",
        "wiz_step2_intro": "Introdu datele aplicației ANAF și CIF-ul firmei. Restul are valori implicite bune.",
        "adv_title": "Setări avansate",
        "adv_hint": "Modifică doar dacă știi ce faci. Callback URL trebuie să fie identic cu cel din profilul OAuth de la ANAF.",
        "choose": "Alege…",
        "folder_hint": "Aici se salvează PDF-urile, pe ani și luni.",
        "test_mode": "Mediu de test — nu se descarcă facturi reale.",
        "wiz_step3_intro": "Ultimul pas: autentificarea se face acum și se repetă o dată la câteva luni.",
        "wiz_done": "Gata. Apasă Sincronizează pentru a descărca facturile.",
        # validation
        "val_required": "Câmp obligatoriu.",
        "val_cif_digits": "CUI: doar cifre (fără RO).",
        "val_environment": "Mediu invalid.",
        "val_fix": "Corectează câmpurile marcate.",
        "val_folder": "Alege un dosar complet (de exemplu cu butonul Alege…).",
        "config_corrupt": "Fișierul de setări este corupt și nu a putut fi citit. Completează și salvează setările din nou.",
        "folder_opened": "Am deschis dosarul în Finder / Explorer.",
        "folder_open_failed": "Nu am putut deschide dosarul. Calea este: {path}",
        "quit_busy": "O sincronizare este în curs. Așteaptă să se termine înainte de a închide aplicația.",
        # error headlines by code
        "err_not_authenticated": "Nu ești autentificat la ANAF. Mergi la Setări → Autentificare ANAF.",
        "err_refresh_failed": "Sesiunea ANAF a expirat. Autentifică-te din nou în Setări.",
        "err_token_exchange_failed": "ANAF a respins codul de autorizare. Reia autentificarea.",
        "err_state_mismatch": "Adresa lipită nu corespunde acestei sesiuni. Reia autentificarea.",
        "err_no_code": "Nu am găsit codul de autorizare în adresa lipită. Copiază adresa completă din bara de adrese.",
        "err_no_config": "Setările sunt incomplete. Completează Client ID, Client secret și CUI.",
        "err_missing_values": "Setările sunt incomplete. Completează Client ID, Client secret și CUI.",
        "err_bad_environment": "Mediul configurat este invalid. Alege Test sau Producție în Setări.",
        "err_network": "Nu s-a putut contacta ANAF. Verifică conexiunea la internet și încearcă din nou.",
        "err_anaf_http": "ANAF a răspuns cu o eroare. Încearcă din nou mai târziu.",
        "err_pdf_failed": "ANAF nu a putut genera PDF-ul pentru această factură. Fișierul original a fost salvat în dosar.",
        "err_bad_download": "Fișierul descărcat de la ANAF este invalid.",
        "err_unknown": "A apărut o eroare neașteptată.",
        "err_csv_locked": "Fișierul invoices.csv este deschis în alt program (Excel?). Închide-l și sincronizează din nou.",
        "err_folder_unwritable": "Nu pot scrie în dosarul pentru facturi. Alege alt dosar în Setări.",
        "err_oauth_access_denied": (
            "ANAF a refuzat accesul: autentificarea cu certificatul nu s-a finalizat. "
            "Setările aplicației nu sunt de vină. Cel mai des ajută: autentifică-te mai întâi pe "
            "pfinternet.anaf.ro cu certificatul, apoi deschide adresa de autorizare în același browser."
        ),
        "err_oauth_access_denied_more": (
            "• Programul certificatului (DigiSign Client, certSIGN Desktop, SafeNet…) este pornit și tokenul USB conectat?\n"
            "• Browserul ți-a cerut să alegi un certificat? Dacă fereastra de selecție nu a apărut, permite pop-up-urile pentru anaf.ro și încearcă din nou. Pe macOS fereastra apare de obicei doar în Chrome sau Safari.\n"
            "• Certificatul este înregistrat în SPV cu drepturi pentru acest CUI, iar firma este înrolată în e-Factura?"
        ),
        "err_oauth_invalid_client": "ANAF nu a acceptat Client ID. Verifică-l în profilul OAuth din portalul ANAF (și că serviciul EFACTURA este bifat).",
        "err_oauth_invalid_request": "ANAF a respins cererea. Cel mai des, Callback URL (în Setări → Setări avansate) nu este identic cu cel înregistrat la ANAF (slash final, http vs https).",
        "err_oauth_other": "ANAF a returnat eroarea „{code}”.",
        # notices
        "notice_legacy_listing": "Listarea paginată nu este disponibilă; se folosește varianta clasică.",
        "notice_date_unknown": "O factură nu are dată; a fost pusă în dosarul lunii curente.",
        "notice_generic": "Informație suplimentară în jurnalul tehnic (ui.log).",
        # log lines
        "ev_started": "Se caută facturile primite în ultimele {days} de zile…",
        "ev_started_test": "Se caută facturile primite în ultimele {days} de zile (mediu de test, CUI {cif})…",
        "ev_listed": "ANAF a raportat {count} documente în această perioadă.",
        "ev_done": "{invoice} — {supplier} ({date})",
        "ev_dup": "Sărită (deja descărcată): {id}",
        "ev_pdf_failed": "{invoice}: ANAF nu a putut genera PDF-ul (fișierul original este salvat).",
        "ev_finished": "Gata. Facturi noi: {new}. Deja descărcate: {dup}. Fără PDF: {pdf}. Erori: {err}.",
        "ev_finished_none": "Gata. Nu sunt facturi noi.",
    },
    "en": {
        "app": "e-Factura Sync",
        "nav_home": "Home",
        "nav_invoices": "Invoices",
        "nav_settings": "Settings",
        "sync": "Synchronize",
        "sync_running": "Sync in progress…",
        "sync_busy": "A sync is already running.",
        "last_sync": "Last sync",
        "never": "Never",
        "total": "Invoices downloaded",
        "this_month": "This month",
        "pdf_failed": "Invoices without PDF",
        "environment": "Environment",
        "recent": "Latest invoices downloaded",
        "log": "Log",
        "open_pdf": "PDF",
        "xml_only": "no PDF",
        "no_pdf": "no PDF",
        "no_pdf_why": "ANAF could not generate the PDF. The original invoice file is in the folder and is valid for accounting.",
        "col_date": "Date",
        "col_invoice": "Invoice",
        "col_supplier": "Supplier",
        "col_type": "Type",
        "credit_note": "credit note",
        "credit_note_long": "Credit note (storno invoice)",
        "invoice": "invoice",
        "filter_month": "Month",
        "filter_supplier": "Supplier",
        "all": "all",
        "filter": "Filter",
        "open_folder": "Open folder",
        "no_invoices": "No invoices downloaded yet. Go to Home and press Synchronize.",
        "no_invoices_filtered": "No invoice matches the filters.",
        "clear_filters": "Clear filters",
        "months": "January,February,March,April,May,June,July,August,September,October,November,December",
        "csv_note": "invoices.csv in the folder lists every invoice — you can send it to your accountant.",
        "settings": "Settings",
        "settings_saved": "Settings saved.",
        "config_needed": "Fill in the settings to get started.",
        "client_id": "Client ID",
        "client_secret": "Client secret",
        "secret_keep": "leave blank to keep the existing value",
        "secret_set": "(set)",
        "cif": "CUI (tax ID)",
        "cif_hint": "digits only, no RO",
        "environment_prod": "Production (real invoices)",
        "environment_test": "Test",
        "redirect_uri": "Callback URL",
        "base_dir": "Invoices folder",
        "save": "Save",
        "auth": "ANAF authentication",
        "auth_yes": "Authenticated",
        "auth_no": "Not authenticated",
        "expires": "valid until {date} (renewed automatically)",
        "auth_begin": "Start authentication",
        "auth_step1": "Open the address below in a browser where your qualified digital certificate is available.",
        "auth_step2": "Authenticate with the certificate and authorize the application.",
        "auth_step3": "The browser will try to open an address that will not load — that is normal. Copy the full address from the address bar and paste it below.",
        "auth_copy_hint": "If you use another browser for the certificate, copy the address and paste it there.",
        "auth_restart": "Start over",
        "auth_not_pending": "The authentication is no longer in progress. Start it again.",
        "new_tab": "(opens in a new tab)",
        "paste": "Paste the redirect address",
        "auth_complete": "Complete",
        "auth_ok": "Authentication successful.",
        "error": "Error",
        "tech_details": "Technical details",
        "language": "Language",
        "quit": "Quit the app",
        "firm": "Firm",
        "copy_url": "Copy address",
        "copied": "Copied.",
        "pdf_retry": "Retry PDF",
        "pdf_retry_all": "Done: {done} PDFs generated, {failed} still without PDF.",
        "pdf_retry_ok": "The PDF was generated.",
        "pdf_retry_all_btn": "Retry all missing PDFs",
        "filter_missing_pdf": "without PDF only",
        "firms": "Firms",
        "firm_name": "Firm name",
        "firm_switch": "Switch firm",
        "firm_add": "Add firm",
        "firm_add_hint": "A new firm's invoices go to Documents/Facturi e-Factura/<firm name>. ANAF authentication is shared: the certificate must have SPV rights for each firm.",
        "firm_select": "Select",
        "firm_selected": "selected",
        "firm_remove": "Remove",
        "firm_added": "Firm “{name}” added and selected.",
        "firm_removed": "Firm removed (downloaded invoices stay in their folder).",
        "firm_last": "This is the last firm; it cannot be removed.",
        "val_firm_new": "Enter the firm name and CUI (digits only).",
        "diag_title": "Diagnostics",
        "diag_hint": "If something goes wrong, send this information (no confidential data) together with a description of the problem.",
        "diag_copy": "Copy diagnostic info",
        "diag_copied": "Copied.",
        "diag_open": "view as text",
        "quit_bye": "The app has quit. You can close this tab. To use it again, open e-Factura Sync as usual.",
        "switch_lang": "Comută pe română",
        "footer_local": "The app runs on your computer at {url}. You can close this tab — the app keeps running.",
        "open_pdf_for": "PDF for invoice {invoice} (opens in a new tab)",
        "choose_folder": "Choose the invoices folder",
        "err_page_expired": "This page has expired, probably because the app was restarted. Reload the page (Cmd+R / F5) and try again.",
        "err_pdf_missing": "The PDF file is no longer in the folder. Open the folder to check, or synchronize again.",
        "err_not_found": "This page does not exist.",
        "err_bad_request": "The request could not be processed. Reload the page and try again.",
        "err_server": "An unexpected error occurred in the app. Reload the page; if it persists, details are in ui.log.",
        "secret_retype": "Re-enter the Client secret — for safety it is not kept in the form.",
        "wiz_title": "First-time setup",
        "wiz_step": "Step {n} of 3",
        "wiz_need_title": "What you need",
        "wiz_need_cert": "A qualified digital certificate (DigiSign, certSIGN, AlfaTrust…) registered in SPV for your company, with e-Factura enabled.",
        "wiz_need_app": "An application registered with ANAF (OAuth profile), which gives you a Client ID and a Client secret:",
        "anaf_api_link": "anaf.ro → API registration page (in Romanian)",
        "wiz_back": "← Back",
        "wiz_app_1": "Go to anaf.ro → „Servicii online” → „Înregistrare aplicații developeri” → „Înregistrare în vederea accesării serviciilor web” (the ANAF portal is Romanian only).",
        "wiz_app_2": "Log in to SPV (Spațiul Privat Virtual, ANAF's taxpayer portal) with the certificate or username/password.",
        "wiz_app_3": "Create an OAuth profile: application name, Callback URL (use https://localhost/callback) and tick the EFACTURA service.",
        "wiz_app_4": "Generate and copy the Client ID and Client secret — you enter them in the next step.",
        "wiz_next": "Continue",
        "wiz_step2_intro": "Enter your ANAF app details and the company CIF. The rest has good defaults.",
        "adv_title": "Advanced settings",
        "adv_hint": "Change these only if you know what you are doing. The Callback URL must match your ANAF OAuth profile exactly.",
        "choose": "Choose…",
        "folder_hint": "PDFs are saved here, by year and month.",
        "test_mode": "Test environment — no real invoices are downloaded.",
        "wiz_step3_intro": "Last step: you authenticate now, and again every few months.",
        "wiz_done": "Done. Press Synchronize to download the invoices.",
        "val_required": "Required field.",
        "val_cif_digits": "CUI: digits only (no RO).",
        "val_environment": "Invalid environment.",
        "val_fix": "Fix the highlighted fields.",
        "val_folder": "Choose a full folder path (for example with the Choose… button).",
        "config_corrupt": "The settings file is corrupt and could not be read. Fill in and save the settings again.",
        "folder_opened": "Opened the folder in Finder / Explorer.",
        "folder_open_failed": "Could not open the folder. The path is: {path}",
        "quit_busy": "A sync is running. Wait for it to finish before quitting the app.",
        "err_not_authenticated": "Not authenticated with ANAF. Go to Settings → ANAF authentication.",
        "err_refresh_failed": "Your ANAF session has expired. Authenticate again in Settings.",
        "err_token_exchange_failed": "ANAF rejected the authorization code. Start the authentication again.",
        "err_state_mismatch": "The pasted address does not belong to this session. Start the authentication again.",
        "err_no_code": "No authorization code found in the pasted address. Copy the full address from the address bar.",
        "err_no_config": "Settings are incomplete. Fill in the Client ID, Client secret and CUI.",
        "err_missing_values": "Settings are incomplete. Fill in the Client ID, Client secret and CUI.",
        "err_bad_environment": "The configured environment is invalid. Choose Test or Production in Settings.",
        "err_network": "Could not reach ANAF. Check your internet connection and try again.",
        "err_anaf_http": "ANAF responded with an error. Try again later.",
        "err_pdf_failed": "ANAF could not generate the PDF for this invoice. The original file was saved in the folder.",
        "err_bad_download": "The file downloaded from ANAF is invalid.",
        "err_unknown": "An unexpected error occurred.",
        "err_csv_locked": "invoices.csv is open in another program (Excel?). Close it and synchronize again.",
        "err_folder_unwritable": "Cannot write to the invoices folder. Choose another folder in Settings.",
        "err_oauth_access_denied": (
            "ANAF denied access: the certificate authentication did not complete. "
            "The app settings are not at fault. What most often helps: log in to pfinternet.anaf.ro "
            "with the certificate first, then open the authorization address in the same browser."
        ),
        "err_oauth_access_denied_more": (
            "• Is the certificate software (DigiSign Client, certSIGN Desktop, SafeNet…) running and the USB token plugged in?\n"
            "• Did the browser ask you to choose a certificate? If no selection window appeared, that is why it failed — allow pop-ups for anaf.ro and try again. On macOS the window usually appears only in Chrome or Safari.\n"
            "• Is the certificate registered in SPV with rights for this CUI, and is the company enrolled in e-Factura?"
        ),
        "err_oauth_invalid_client": "ANAF did not accept the Client ID. Check it in the OAuth profile on the ANAF portal (and that the EFACTURA service is ticked).",
        "err_oauth_invalid_request": "ANAF rejected the request. Most often the Callback URL (Settings → Advanced settings) is not identical to the one registered with ANAF (trailing slash, http vs https).",
        "err_oauth_other": "ANAF returned the error “{code}”.",
        "notice_legacy_listing": "Paginated listing is unavailable; using the classic listing.",
        "notice_date_unknown": "An invoice has no date; it was filed under the current month.",
        "notice_generic": "Additional information is in the technical log (ui.log).",
        "ev_started": "Looking for invoices received in the last {days} days…",
        "ev_started_test": "Looking for invoices received in the last {days} days (test environment, CUI {cif})…",
        "ev_listed": "ANAF reported {count} documents for this period.",
        "ev_done": "{invoice} — {supplier} ({date})",
        "ev_dup": "Skipped (already downloaded): {id}",
        "ev_pdf_failed": "{invoice}: ANAF could not generate the PDF (the original file is saved).",
        "ev_finished": "Done. New invoices: {new}. Already downloaded: {dup}. Without PDF: {pdf}. Errors: {err}.",
        "ev_finished_none": "Done. No new invoices.",
    },
}

LANGUAGES = tuple(STRINGS)


class Translator:
    def __init__(self, lang: str):
        self.lang = lang if lang in STRINGS else "ro"
        self.table = STRINGS[self.lang]

    def has(self, key: str) -> bool:
        return key in self.table or key in STRINGS["ro"]

    def __call__(self, key: str, **fmt) -> str:
        text = self.table.get(key) or STRINGS["ro"].get(key, key)
        return text.format(**fmt) if fmt else text


def translator(lang: str) -> Translator:
    return Translator(lang)
